import React, { useEffect } from "react";
import {
  View,
  Text,
  ActivityIndicator,
  StyleSheet,
  TouchableOpacity,
  Platform,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { WebView } from "react-native-webview";
import { Feather } from "@expo/vector-icons";
import { useDesignMode } from "../../context/DesignModeContext";
import { FontSizes, Spacing, Radius } from "../../theme/tokens";

interface Props {
  navigation: any;
  route: any;
}

/**
 * Strips any null/undefined/empty values from the payment data object.
 * IMPORTANT: We do NOT recalculate or replace the signature here.
 * The signature has already been correctly generated by the edge function
 * using the right passphrase and parameter order. Recalculating it client-side
 * would produce a different (incorrect) hash, causing PayFast to reject the request.
 */
function cleanPayFastData(data: Record<string, string>): Record<string, string> {
  const cleaned: Record<string, string> = {};
  for (const key of Object.keys(data)) {
    const val = data[key];
    if (val !== undefined && val !== null && String(val).trim() !== "") {
      cleaned[key] = String(val).trim();
    }
  }
  return cleaned;
}

export default function PayFastCheckoutScreen({ navigation, route }: Props) {
  const { colors, font, isWireframe: isWF } = useDesignMode();
  const { paymentUrl = "https://sandbox.payfast.co.za/eng/process", paymentData: rawPaymentData = {}, orderId } = route.params || {};

  // Use the server-provided signature directly — do NOT recalculate
  const paymentData = cleanPayFastData(rawPaymentData);

  // Escape helper
  const escapeHtml = (value: string): string => {
    return String(value || "")
      .replace(/&/g, "&amp;")
      .replace(/"/g, "&quot;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
  };

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      margin: 0;
      background-color: #F8F9FA;
      color: #333333;
    }
    .loader {
      border: 4px solid #f3f3f3;
      border-top: 4px solid #00B4D8;
      border-radius: 50%;
      width: 40px;
      height: 40px;
      animation: spin 1s linear infinite;
      margin-bottom: 16px;
    }
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
  </style>
</head>
<body>
  <div class="loader"></div>
  <p style="font-weight: 500; font-size: 15px;">Connecting securely to PayFast...</p>
  <form id="payfast_form" method="POST" action="${escapeHtml(paymentUrl)}">
    ${Object.entries(paymentData)
      .map(
        ([key, value]) =>
          `<input type="hidden" name="${escapeHtml(key)}" value="${escapeHtml(String(value))}" />`
      )
      .join("\n    ")}
  </form>
  <script>
    setTimeout(function() {
      var f = document.getElementById('payfast_form');
      if (f) f.submit();
    }, 150);
  </script>
</body>
</html>
`;

  // For Web: auto submit form into window or iframe
  useEffect(() => {
    if (Platform.OS === "web" && paymentUrl && paymentData) {
      try {
        const form = document.createElement("form");
        form.method = "POST";
        form.action = paymentUrl;
        form.target = "_self";

        Object.entries(paymentData).forEach(([key, val]) => {
          const input = document.createElement("input");
          input.type = "hidden";
          input.name = key;
          input.value = String(val);
          form.appendChild(input);
        });

        document.body.appendChild(form);
        form.submit();
      } catch (err) {
        console.error("Web PayFast auto-submit error:", err);
      }
    }
  }, [paymentUrl, paymentData]);

  const handleClose = () => {
    navigation.goBack();
  };

  const handleNavigationChange = (navState: any) => {
    const url = navState.url || "";
    console.log("PayFast navigation URL:", url);

    if (
      url.includes("payfast-return") ||
      url.includes("return") ||
      url.includes("success")
    ) {
      if (orderId) {
        navigation.replace("OrderPlaced", { orderId });
      } else {
        navigation.navigate("HomeTab");
      }
    } else if (
      url.includes("payfast-cancel") ||
      url.includes("cancel")
    ) {
      navigation.goBack();
    }
  };

  return (
    <SafeAreaView
      style={[
        styles.container,
        { backgroundColor: isWF ? "#F0F0F0" : colors.warmAsh },
      ]}
      edges={["top", "left", "right"]}
    >
      <View
        style={[
          styles.header,
          {
            backgroundColor: isWF ? "#FFFFFF" : colors.white,
            borderBottomColor: isWF ? "#E0E0E0" : colors.divider,
          },
        ]}
      >
        <TouchableOpacity onPress={handleClose} style={styles.closeBtn}>
          <Feather
            name="x"
            size={22}
            color={isWF ? "#333333" : colors.charcoalInk}
          />
        </TouchableOpacity>
        <Text
          style={[
            styles.title,
            {
              color: isWF ? "#1A1A1A" : colors.charcoalInk,
              fontFamily: font("bodyMedium"),
            },
          ]}
        >
          Secure PayFast Payment
        </Text>
        <View style={{ width: 40 }} />
      </View>

      {Platform.OS === "web" ? (
        <View style={styles.webContainer}>
          <ActivityIndicator size="large" color={colors.petrolDeep} />
          <Text
            style={[
              styles.webText,
              { color: colors.charcoalInk, fontFamily: font("body") },
            ]}
          >
            Redirecting to PayFast Secure Checkout...
          </Text>
          <TouchableOpacity
            style={[
              styles.manualBtn,
              { backgroundColor: colors.petrolDeep, borderRadius: Radius.md },
            ]}
            onPress={() => {
              if (paymentUrl && paymentData) {
                const form = document.createElement("form");
                form.method = "POST";
                form.action = paymentUrl;
                form.target = "_self";
                Object.entries(paymentData).forEach(([key, val]) => {
                  const input = document.createElement("input");
                  input.type = "hidden";
                  input.name = key;
                  input.value = String(val);
                  form.appendChild(input);
                });
                document.body.appendChild(form);
                form.submit();
              }
            }}
          >
            <Text style={{ color: "#FFFFFF", fontFamily: font("bodyMedium") }}>
              Click here if you are not redirected automatically
            </Text>
          </TouchableOpacity>
        </View>
      ) : (
        <View style={{ flex: 1 }}>
          <WebView
            source={{ html }}
            originWhitelist={["*"]}
            javaScriptEnabled={true}
            domStorageEnabled={true}
            mixedContentMode="always"
            startInLoadingState
            renderLoading={() => (
              <View style={styles.loadingContainer}>
                <ActivityIndicator size="large" color={colors.petrolDeep} />
              </View>
            )}
            onNavigationStateChange={handleNavigationChange}
          />
        </View>
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.sm,
    borderBottomWidth: 1,
  },
  closeBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: FontSizes.md,
  },
  loadingContainer: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8F9FA",
  },
  webContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  webText: {
    fontSize: FontSizes.base,
    marginTop: Spacing.sm,
  },
  manualBtn: {
    marginTop: Spacing.md,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.lg,
  },
});
